-- MySQL Script generated by MySQL Workbench
-- Tue Jul 19 17:31:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema boardgameshelf
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema boardgameshelf
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `boardgameshelf` DEFAULT CHARACTER SET utf8 ;
USE `boardgameshelf` ;

-- -----------------------------------------------------
-- Table `boardgameshelf`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boardgameshelf`.`user` ;

CREATE TABLE IF NOT EXISTS `boardgameshelf`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `boardgameshelf`.`boardgame`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boardgameshelf`.`boardgame` ;

CREATE TABLE IF NOT EXISTS `boardgameshelf`.`boardgame` (
  `boardgame_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`boardgame_id`));


-- -----------------------------------------------------
-- Table `boardgameshelf`.`list_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boardgameshelf`.`list_category` ;

CREATE TABLE IF NOT EXISTS `boardgameshelf`.`list_category` (
  `list_category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`list_category_id`));


-- -----------------------------------------------------
-- Table `boardgameshelf`.`list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boardgameshelf`.`list` ;

CREATE TABLE IF NOT EXISTS `boardgameshelf`.`list` (
  `list_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `list_category_id` INT NOT NULL,
  PRIMARY KEY (`list_id`),
  INDEX `fk_list_category1_idx` (`list_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_list_category1`
    FOREIGN KEY (`list_category_id`)
    REFERENCES `boardgameshelf`.`list_category` (`list_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `boardgameshelf`.`user_has_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boardgameshelf`.`user_has_list` ;

CREATE TABLE IF NOT EXISTS `boardgameshelf`.`user_has_list` (
  `user_id` INT NOT NULL,
  `list_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `list_id`),
  INDEX `fk_user_has_list_list1_idx` (`list_id` ASC) VISIBLE,
  INDEX `fk_user_has_list_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_list_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `boardgameshelf`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_list_list1`
    FOREIGN KEY (`list_id`)
    REFERENCES `boardgameshelf`.`list` (`list_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `boardgameshelf`.`list_has_boardgame`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boardgameshelf`.`list_has_boardgame` ;

CREATE TABLE IF NOT EXISTS `boardgameshelf`.`list_has_boardgame` (
  `list_id` INT NOT NULL,
  `boardgame_id` INT NOT NULL,
  PRIMARY KEY (`list_id`, `boardgame_id`),
  INDEX `fk_list_has_boardgame_boardgame1_idx` (`boardgame_id` ASC) VISIBLE,
  INDEX `fk_list_has_boardgame_list1_idx` (`list_id` ASC) VISIBLE,
  CONSTRAINT `fk_list_has_boardgame_list1`
    FOREIGN KEY (`list_id`)
    REFERENCES `boardgameshelf`.`list` (`list_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_list_has_boardgame_boardgame1`
    FOREIGN KEY (`boardgame_id`)
    REFERENCES `boardgameshelf`.`boardgame` (`boardgame_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
