-- MySQL Script generated by MySQL Workbench
-- Wed Jul 20 09:55:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema boardgameshelf
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema boardgameshelf
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `boardgameshelf` DEFAULT CHARACTER SET utf8 ;
USE `boardgameshelf` ;

-- -----------------------------------------------------
-- Table `boardgameshelf`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boardgameshelf`.`user` ;
DROP TABLE IF EXISTS `boardgameshelf`.`boardgame` ;
DROP TABLE IF EXISTS `boardgameshelf`.`user_has_boardgame` ;


CREATE TABLE IF NOT EXISTS `boardgameshelf`.`user` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `hashedpassword` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);

INSERT INTO `user` (`id`, `name`, `email`, `hashedpassword`) VALUES
(1, 'Jean Jean', 'jean.jean@jeanmail.com', '$argon2id$v=19$m=65536,t=5,p=1$wCiUeYdaDWDCX7ZQ2qKFng$pYxPOsrdfo9p2XJO6st7h60EIL++m2j+o/AS58W8dMo'),
(2, 'Benoyt', 'benoyt.vendanges@caramail.com', '$argon2id$v=19$m=65536,t=5,p=1$wCiUeYdaDWDCX7ZQ2qKFng$pYxPOsrdfo9p2XJO6st7h60EIL++m2j+o/AS58W8dMo');
-- -----------------------------------------------------
-- Table `boardgameshelf`.`boardgame`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `boardgameshelf`.`boardgame` (
  `boardgame_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `min_players` INT NOT NULL,
  `max_players` INT NOT NULL,
  `min_playtime` INT NOT NULL,
  `max_playtime` INT NOT NULL,
  `min_age` INT NOT NULL,
  `description` LONGTEXT NOT NULL,
  `image_url` VARCHAR(255) NOT NULL,
  `rank` INT NOT NULL,
  `year_published` INT NOT NULL,
  `categories` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`boardgame_id`));

INSERT INTO `boardgame` (`boardgame_id`, `name`, `min_players`, `max_players`, `min_playtime`, `max_playtime`, `min_age`, `image_url`, `rank`, `year_published`, `categories`, `description`) VALUES
(1, 'Catan', 3, 4, 45, 90, 10, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1629324722072.jpg', 22, 1995, "family, dice, negotiation, economic", "The women and men of your expedition build the first two settlements. Fortunately, the land is rich in natural resources. You build roads and new settlements that eventually become cities. Will you succeed in gaining supremacy on Catan? Barter trade dominates the scene. Some resources you have in abundance, other resources are scarce. Ore for wool, brick for lumber - you trade according to what is needed for your current building projects."),
(2, 'Mysterium', 2, 7, 30, 60, 10, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559255824772-51iPxTb5g7L.jpg', 71, 2015, "deduction, party, coop", "A horrible crime has been committed on the grounds of Warwick Manor and it's up to the psychic investigators to get to the bottom of it."),
(3, 'Perudo', 2, 6, 15, 30, 8, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1607267427395', 561, 2002, "bluff, dice, party", "Dice-based bluffing game with two twists. On your turn, either: 1. Increase the bid of dice, in quantity at a value or in value at a quantity; 2. call the bluff of the previous player, with all dice being revealed from under players' cups."),
(4, 'Clank', 2, 4, 30, 60, 13, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254970101-61gHdS3ds2L.jpg', 33, 2012, "deckbuilding, card, strategy", "Sneak into an angry dragon's mountain lair to steal precious artifacts. Delve deeper to find more valuable loot. Acquire cards for your deck and watch your thievish abilities grow."),
(5, 'Dixit', 3, 6, 30, 42, 8, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1629320890677.jpg', 58, 2008, "abstract, card, party, deduction", "Each player is the storyteller in turn. The storyteller chooses a card from their hand and gives a clue (word, phrase, song...). The other players choose the card in their hand that best fits this clue. The Storyteller’s card is shuffled with the players’ cards, then all the chosen cards are revealed. Which is the storyteller’s card?"),
(6, 'King Domino', 2, 4, 15, 20, 8, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254188772-515tbFJ5C8L.jpg', 28, 2016, "family, city, tile", "A 2-4 player strategy game that plays like dominoes with a kingdom-building twist. Each turn you will connect a new domino to your existing kingdom, making sure that at least one of its sides connects to a matching element already in play."),
(7, '7 Wonders', 2, 7, 30, 45, 10, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559253945470-61dlm9QcXpL.jpg', 11, 2010, "card, city, draft, strategy", "You are the leader of one of the 7 great cities of the Ancient World. Gather resources, develop commercial routes and affirm your military supremacy. Build your city and erect an architectural wonder which will transcend future times!"),
(8, 'Skull & Roses', 3, 6, 15, 45, 8, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1629324722072.jpg', 119, 2011, "bluff, negotiation, party, deduction", "An ancient game of ornate skulls and dangerous roses, Skull is simple to learn but dangerously difficult to win. You must bluff, lie and pierce through the deceptions to expose the roses. Be wary, though - if you happen across a skull, the consequences are dire"),
(9, 'Time Bomb', 4, 8, 1, 30, 10, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1567443476036', 324, 2016, "party, hidden, negotiation", "Each player will be assigned a secret identity, Agent or Terrorist. The game will unroll in a maximum of four rounds in which the agents want to defuse the bomb and the terrorists want it to explode."),
(10, 'Fertility', 2, 4, 25, 45, 10, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1545094448940', 456, 2018, "family, tile, strategy, city", "You are a Nomarch in Ancient Egypt. The Pharaoh put you in charge of a Metropolis and its region. The flooding of the Nile is coming to an end and the lands of the Valley are ready to offer their riches. Organize the collection of resources, build districts with the most lucrative shops, supply them with goods and earn the most Debens for the glory of the Pharaoh. The player who will make the best use of the resources of the Nile Valley will win the game."),
(11, 'Top Ten', 4, 9, 30, 30, 14, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/userfiles/1653420234971-Top_ten_3dGameBox.jpg', 79, 2020, "party, abstract, coop, fun", "A fun co-op game! For each theme (funny or surprising), each player has to invent a response. But the intensity of the answer has to correspond to his secret number. Then, if the Cap’ten puts the answers in the correct order, the team wins!"),
(12, 'Dobble', 2, 8, 6, 18, 6, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1629322564445.jpg', 465, 2009, "family, card, agility", "There is always one, and only one, matching symbol between any 2 cards in this party game. Spot it and you win!."),
(13, 'Times Up', 4, 18, 45, 90, 12, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559257781337-41wxuhziKqL.jpg', 1123, 1999, "party, abstract, fun", "The party-perfect celebrity charades game that builds the laughter and excitement in three hilarious rounds. You have 30 seconds to get your team to guess as many celebrity names in the Deck of Fame as possible."),
(14, 'Paper Tales', 2, 5, 30, 45, 12, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254161320-51OXWRLAE5L.jpg', 690, 2017, "draft, card, strategy, city", "Experience centuries of fantasy kingdoms in Paper Tales! Transform characters and buildings in each period based on your developments and the age of your heroes. Write a new legend of the rightful ruler who brought unity to the rival kingdoms!"),
(15, 'Everdell', 1, 4, 20, 80, 10, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1574877074147', 18, 2018, "card, city, strategy", "From Everfrost to Bellsong, many a peaceful year have passed in Everdell — but the time has come for new territories to be settled and new cities to be established. You will be the leader of a group of critters intent on just such a task. There are buildings to construct, lively characters to meet, events to host— you will have a busy year ahead of you!"),
(16, 'The resistance', 5, 10, 30, 45, 13, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1622150592383', 70, 2009, "bluff, card, deduction, party", "The Empire must fall. Our mission must succeed. By destroying their key bases, we will shatter Imperial strength and liberate our people. Yet spies have infiltrated our ranks, ready for sabotage. We must unmask them. In five nights we reshape destiny or die trying. We are the Resistance!"),
(17, 'Stella', 3, 6, 30, 40, 7, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1634412897712', 876, 2021, "family, card, abstract", "A competitive game in the Dixit Universe, where players interpret pictures after receiving a common word. Choose the same pictures as the other players to achieve victory"),
(18, 'Ricochet Robots', 1, 15, 5, 30, 13, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1633105252133', 871, 1999, "abstract, deduction", " There's a four-piece modular board that forms a large room with walls spread around the board. There are also color-coded targets on boards."),
(19, 'Res Arcana', 2, 4, 20, 60, 12, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1629324263854.jpg', 159, 2019, "card, deckbuilding, strategy", "2-4 alchemical mages vie for control of ancient monuments and places of power. Use your magical essences and items to build artifacts, activate their powers, and command dragons. The mage with the most victory points"),
(20, 'Santorini', 2, 4, 15, 30, 8, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1577065005762', 25, 2016, "abstract, strategy, city", "A fantastic reimagining of the classic abstract game from 2004. Players are given a sandbox in which to play as gods, moving their workers around the board to build up a beautiful, multi-tiered city. Do you have what it takes to outsmart your opponents?"),
(21, 'Star Realms', 2, 2, 15, 30, 12, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1633547115096', 1785, 2014, "card, deckbuilding", "Star Realms offers all the thrills of traditional trading card game style combat, combined with the fun of a deck building game. Play powerful ships, destroy enemy bases or blast your opponent directly on your way to victory!"),
(22, 'Root', 2, 4, 60, 90, 10, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1540147295104', 1, 2018, "strategy, card, dice, economic", "Find adventure in this marvelous asymmetric game. Root provides limitless replay value as you and your friends explore the unique factions all wanting to rule a fantastic forest kingdom."),
(23, 'Scythe', 1, 5, 90, 120, 14, 'https://cdn.shopify.com/s/files/1/0513/4077/1515/products/scythe-board-game.jpg?v=1611090922', 2, 2016, "city, strategy, card", "Each encounter card provides the player with several options, allowing them to mitigate the luck of the draw through their selection. Combat is also driven by choices, not luck or randomness."),
(24, 'Azul', 2, 4, 30, 60, 8, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254200327-61EFZADvURL.jpg', 6, 2017, "abstract, strategy, family", "Players compete as artisans decorating the walls of the royal Palace of Dvora. By carefully drafting the correct Quantity and style of tiles, the most clever of artisans plan ahead to maximize the beauty of their work (not to mention their scores!) while ensuring they wasted no supplies in the process."),
(25, 'Splendor', 2, 4, 30, 60, 10, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254164722-51AHDwGznvL.jpg', 15, 2014, "card, strategy, family", "As a wealthy Renaissance merchant, acquire mines and transportation, hire artisans and woo the nobility. Create the most fantastic jewelry to become the best-known merchant of them all! Acquire precious stones to trade them for development cards. Use development cards to acquire more gem stones."),
(26, 'Ticket To Ride', 2, 5, 45, 90, 10, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1629324738308.jpg', 19, 2004, "family, card, economic", "A cross-country train adventure game. Players collect train cards that enable them to claim railway routes connecting cities throughout North America. The longer the routes, the more points they earn."),
(27, 'Pandemic Legacy', 2, 4, 60, 75, 13, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559257833516-612BUfjuA7fL.jpg', 16, 2018, "coop, dice, negotiation", ">The world is on the brink of disaster. In Pandemic Legacy, your disease-fighting team must keep four deadly diseases at bay for a whole year. Each month will bring new surprises, and your actions in each game will have repercussions on the next. Will you let cities fall to the diseases?"),
(28, 'Codenames', 2, 8, 15, 25, 10, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254183526-51f6ysXCMmL.jpg', 12, 1995, "deduction, party, city", "The two rival spymasters know the secret identities of 25 agents. Their teammates know the agents only by their CODENAMES.The teams compete to see who can make contact with all of their agents first. "),
(29, '7 wonders Duel', 2, 2, 30, 45, 10, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1629323024736.jpg', 10, 2015, "card, city, strategy", "Experience an intense two-player struggle for supremacy in the ancient world!Designed by Antoine Bauza and Bruno Cathala, 7 Wonders: Duel adapts the game play and excitement of 7 Wonders for one-on- one battles."),
(30, 'Smallworld', 2, 5, 40, 80, 8, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254992240-511JJsfrrNL.jpg', 39, 2009, "family, strategy, economic", "In Small World, players will be able to control characters from 14 fantasy races - dwarves, giants, orcs, elves, and so forth - while trying to take control of territory and push opponents out of adjacent lands and off the map. Even while dominating opponents, however, you have to keep in mind that your race's civilization is doomed as well."),
(31, 'The Crew', 2, 5, 20, 20, 10, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1629323334081.jpg', 62, 2019, "coop, card, deduction", "What about the rumors about the unknown planet about? The eventful journey through space extends over 50 exciting missions. But this game can only be defeated by meeting common individual tasks of each player. In order to meet the varied challenges, communication is essential in the team. But this is more difficult than expected in space."),
(32, 'Schotten Totten', 2, 2, 15, 30, 8, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1539385089103', 426, 1999, "abstract, card", "A warm spring breeze flows through the valley as the birds begin to sing and the snow slowly melts away. Your precious village is slowly uncovered and the stone lines that define your property become visible."),
(33, 'Dominion', 2, 4, 30, 30, 13, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254200326-6135RVKbZZL.jpg', 75, 2008, "deckbuilding, card, strategy", "You are a monarch, like your parents before you, a ruler of a small pleasant kingdom of rivers and evergreens. Unlike your parents, however, you have hopes and dreams! You want a bigger and more pleasant kingdom, with more rivers and a wider variety of trees."),
(34, 'Unlock', 1, 6, 45, 75, 10, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254924844-51GjPSrcFbL.jpg', 891, 2017, "family, coop, abstract", "The Department has lost contact with one of their chemists, Dr. Hoffman. In Unlock! The Formula, your mission is to retrieve the truth serum he had been developing. Deep in the New York subway tunnels, you must seek out his laboratory, locate the doctor, and recover the formula before time runs out. The clock is ticking..."),
(35, 'The Mind', 2, 5, 45, 75, 13, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1629321633172.jpg', 22, 2020, "card, coop, abstract", "Working from the shadows, Mind MGMT once used its psychically-powered agents to put a stop to global crises. However, absolute power corrupts absolutely, and Mind MGMT is now rotting from the inside. To tighten its iron grip on the world stage, Mind MGMT deploys covert operatives around the world to recruit other psychically-attuned individuals to their side."),
(36, 'Sushi Go', 2, 8, 30, 45, 8, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254183526-61DkuJEhUWL.jpg', 54, 2016, "family, dice", "Sushi Go!, is a party platter of mega maki, super sashimi, and endless edamame. You still earn points by picking winning sushi combos, but now you can customize each game by choosing a la carte from a menu of more than twenty delectable dishes.");
-- -----------------------------------------------------
-- Table `boardgameshelf`.`user_has_boardgame`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `boardgameshelf`.`user_has_boardgame` (
  `user_id` INT NOT NULL,
  `boardgame_boardgame_id` INT NOT NULL,
  `has` TINYINT NULL,
  `favorite` TINYINT NULL,
  PRIMARY KEY (`user_id`, `boardgame_boardgame_id`),
  INDEX `fk_user_has_boardgame_boardgame1_idx` (`boardgame_boardgame_id` ASC) VISIBLE,
  INDEX `fk_user_has_boardgame_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_boardgame_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `boardgameshelf`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_boardgame_boardgame1`
    FOREIGN KEY (`boardgame_boardgame_id`)
    REFERENCES `boardgameshelf`.`boardgame` (`boardgame_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


INSERT INTO `user_has_boardgame` (`user_id`, `boardgame_boardgame_id`, `has`, `favorite`) VALUES
(1, 1, 1, 0),
(1, 2, 1, 1),
(1, 3, 1, 0),
(1, 4, 1, 0),
(1, 5, 1, 0),
(1, 6, 1, 1),
(1, 7, 1, 0),
(1, 8, 1, 1),
(1, 9, 1, 0),
(1, 10, 1, 0),
(1, 11, 1, 1),
(1, 12, 1, 0),
(1, 13, 1, 0),
(1, 14, 1, 1),
(1, 15, 1, 1),
(1, 16, 1, 0),
(1, 17, 1, 0),
(1, 18, 1, 0),
(1, 19, 0, 0),
(1, 20, 0, 0),
(1, 21, 0, 0),
(1, 22, 0, 0),
(1, 23, 0, 0),
(1, 24, 0, 0),
(2, 25, 0, 0),
(2, 26, 0, 0),
(2, 27, 0, 1),
(2, 28, 0, 0),
(2, 29, 0, 1),
(2, 30, 0, 0),
(2, 31, 0, 0);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
